In [2]:
import numpy as np
import cv2
import json
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


In [ ]:
# Function to get screen width and height
def get_screen_dimensions():
    screen_width, screen_height = 1920, 1080  # Default values (replace with actual dimensions)
    if platform.system() == "Windows":
        try:
            import ctypes
            user32 = ctypes.windll.user32
            screen_width = user32.GetSystemMetrics(0)
            screen_height = user32.GetSystemMetrics(1)
        except:
            pass
    return screen_width, screen_height

In [3]:
# JSON file path
json_file_path = "iris_data.json"

# Load data from the JSON file
with open(json_file_path, "r") as json_file:
    json_data = json.load(json_file)


In [4]:
# Extract features (iris positions) and labels (circle positions)
iris_left = np.array([(point["x"]/, point["y"]) for point in json_data["left_irises"]])
iris_right = np.array([(point["x"], point["y"]) for point in json_data["right_irises"]])
circles = np.array([(point["x"], point["y"]) for point in json_data["circles"]])

In [13]:
print(iris_left)
print(iris_right)
print(circles)

[[391 199]
 [383 201]
 [407 198]
 [408 217]
 [365 219]
 [381 198]
 [372 207]
 [394 208]
 [360 208]
 [345 207]
 [342 217]
 [381 216]
 [386 212]
 [366 217]
 [362 215]
 [344 209]
 [362 214]]
[[424 194]
 [417 196]
 [438 193]
 [440 214]
 [400 216]
 [418 192]
 [408 202]
 [430 203]
 [393 205]
 [378 204]
 [375 215]
 [411 214]
 [417 208]
 [399 214]
 [394 211]
 [378 207]
 [396 212]]
[[ 11  10]
 [321  10]
 [  8   8]
 [  9 473]
 [631 468]
 [628   8]
 [630 470]
 [ 10 470]
 [320 239]
 [630   9]
 [630 469]
 [ 13 471]
 [ 11   7]
 [323 238]
 [318 239]
 [630   9]
 [320 239]]


In [17]:
iris_positions = np.concatenate((iris_left, iris_right), axis=1)
print(iris_positions)

[[391 199 424 194]
 [383 201 417 196]
 [407 198 438 193]
 [408 217 440 214]
 [365 219 400 216]
 [381 198 418 192]
 [372 207 408 202]
 [394 208 430 203]
 [360 208 393 205]
 [345 207 378 204]
 [342 217 375 215]
 [381 216 411 214]
 [386 212 417 208]
 [366 217 399 214]
 [362 215 394 211]
 [344 209 378 207]
 [362 214 396 212]]


In [19]:
# Combine iris positions and circles to form the feature matrix
features = np.concatenate((iris_positions, circles), axis=1)
features


array([[391, 199, 424, 194,  11,  10],
       [383, 201, 417, 196, 321,  10],
       [407, 198, 438, 193,   8,   8],
       [408, 217, 440, 214,   9, 473],
       [365, 219, 400, 216, 631, 468],
       [381, 198, 418, 192, 628,   8],
       [372, 207, 408, 202, 630, 470],
       [394, 208, 430, 203,  10, 470],
       [360, 208, 393, 205, 320, 239],
       [345, 207, 378, 204, 630,   9],
       [342, 217, 375, 215, 630, 469],
       [381, 216, 411, 214,  13, 471],
       [386, 212, 417, 208,  11,   7],
       [366, 217, 399, 214, 323, 238],
       [362, 215, 394, 211, 318, 239],
       [344, 209, 378, 207, 630,   9],
       [362, 214, 396, 212, 320, 239]])

In [4]:
import pygetwindow as gw

# Print all window titles
all_titles = [window.title for window in gw.getAllTitles()]
print("All Window Titles:", all_titles)

# Try to find the window with the specified title
window_title = 'Gaze Tracking'  # Update with your actual window title
windows = gw.getWindowsWithTitle("<built-in method title of str object at 0x000001707F5B8030>")

if windows:
    # Get the first window with the specified title
    screen = windows[0]
    print(f"Window found: {screen.title}")
    screen_width = screen.width
    screen_height = screen.height
else:
    print(f"No window found with title: {window_title}")


All Window Titles: [<built-in method title of str object at 0x000001707F5B8030>, <built-in method title of str object at 0x000001707F5B8030>, <built-in method title of str object at 0x00000170040C5A10>, <built-in method title of str object at 0x00000170041B1B10>, <built-in method title of str object at 0x000001707F5B8030>, <built-in method title of str object at 0x0000017003F3DA70>, <built-in method title of str object at 0x000001707F5B8030>, <built-in method title of str object at 0x000001707F5B8030>, <built-in method title of str object at 0x000001707F5B8030>, <built-in method title of str object at 0x000001707F5B8030>, <built-in method title of str object at 0x00000170041BF570>, <built-in method title of str object at 0x00000170041BEA70>, <built-in method title of str object at 0x00000170041858F0>, <built-in method title of str object at 0x000001707F5B8030>, <built-in method title of str object at 0x000001707F5B8030>, <built-in method title of str object at 0x00000170041BE370>]
No w